parameters :
  locale: fr
  
  mantis_database_host: ''
  mantis_database_port: ''
  mantis_database_user: ''
  mantis_database_password: ''
  mantis_database_name: ''

  symfony_database_host: ''
  symfony_database_port: ''
  symfony_database_user: ''
  symfony_database_password: ''
  symfony_database_name: ''
